import type { Engineer } from './types';

export const sampleEngineers: Engineer[] = [
  {
    rank: 1,
    username: 'macobo',
    avatar_url: 'https://github.com/macobo.png',
    score: 94.7,
    persona_tag: 'The Architect',
    leverage_multiplier: 1.2,
    breakdown: {
      pr_score: 42.3,
      review_score: 31.8,
      issue_score: 12.2,
      pr_count: 12,
      review_count: 28,
      issue_count: 3,
      avg_complexity: 1.4,
    },
    why: 'Drives foundational changes across the query engine and data pipeline layers. Consistently authors high-complexity PRs that unblock multiple teams.',
    top_prs: [
      { title: 'Refactor HogQL query engine for subquery support', complexity: 1.8, number: 18942 },
      { title: 'Add batch export reliability improvements', complexity: 1.5, number: 19201 },
      { title: 'Pipeline: support async transformations in exports', complexity: 1.2, number: 19087 },
    ],
  },
  {
    rank: 2,
    username: 'pauldambra',
    avatar_url: 'https://github.com/pauldambra.png',
    score: 87.3,
    persona_tag: 'The Guardian',
    leverage_multiplier: 1.2,
    breakdown: {
      pr_score: 28.5,
      review_score: 41.2,
      issue_score: 10.1,
      pr_count: 8,
      review_count: 35,
      issue_count: 2,
      avg_complexity: 0.9,
    },
    why: 'Reviewed 35 PRs across the team, more than 2x their own PR output. Acts as the quality backbone of the SDK and ingestion layers.',
    top_prs: [
      { title: 'Fix session recording payload ordering edge case', complexity: 1.3, number: 19054 },
      { title: 'Harden event ingestion retry logic', complexity: 1.1, number: 18876 },
      { title: 'Add SDK integration tests for feature flags', complexity: 0.8, number: 19112 },
    ],
  },
  {
    rank: 3,
    username: 'tiina303',
    avatar_url: 'https://github.com/tiina303.png',
    score: 81.9,
    persona_tag: 'The Closer',
    leverage_multiplier: 1.0,
    breakdown: {
      pr_score: 38.7,
      review_score: 18.4,
      issue_score: 17.3,
      pr_count: 15,
      review_count: 9,
      issue_count: 4,
      avg_complexity: 1.0,
    },
    why: 'Resolved 4 issues, driving a significant share of the project\'s bug-fix and feature-delivery throughput; with 9 code reviews.',
    top_prs: [
      { title: 'New dashboard templates and layout engine', complexity: 1.6, number: 19188 },
      { title: 'Insights: add comparison mode for funnels', complexity: 1.2, number: 18995 },
      { title: 'Fix timezone handling in date range picker', complexity: 0.7, number: 19233 },
    ],
  },
  {
    rank: 4,
    username: 'benjackwhite',
    avatar_url: 'https://github.com/benjackwhite.png',
    score: 76.4,
    persona_tag: 'The Machine',
    leverage_multiplier: 1.0,
    breakdown: {
      pr_score: 44.1,
      review_score: 15.3,
      issue_score: 8.8,
      pr_count: 22,
      review_count: 7,
      issue_count: 2,
      avg_complexity: 0.8,
    },
    why: 'Shipped 22 PRs with an avg complexity of 0.8, maintaining high raw output; with 7 code reviews.',
    top_prs: [
      { title: 'Session replay: network tab performance overhaul', complexity: 1.5, number: 19301 },
      { title: 'Replay: add console log filtering and search', complexity: 1.1, number: 19155 },
      { title: 'Optimize replay list query for large datasets', complexity: 0.9, number: 19078 },
    ],
  },
  {
    rank: 5,
    username: 'liyiy',
    avatar_url: 'https://github.com/liyiy.png',
    score: 72.1,
    persona_tag: 'The Polymath',
    leverage_multiplier: 1.0,
    breakdown: {
      pr_score: 29.6,
      review_score: 22.8,
      issue_score: 13.2,
      pr_count: 10,
      review_count: 11,
      issue_count: 3,
      avg_complexity: 1.0,
    },
    why: 'Balanced contributor across code, reviews, and issue resolution; with 11 code reviews.',
    top_prs: [
      { title: 'Notebooks: collaborative editing with conflict resolution', complexity: 1.4, number: 19267 },
      { title: 'Feature flags: add multivariate percentage validation', complexity: 1.0, number: 18901 },
      { title: 'Billing: usage limit warning notifications', complexity: 0.7, number: 19189 },
    ],
  },
];
